baseURL = "https://intersect88.github.io/napoli-software-webpage/"
languageCode = "it-it"
title = "Napoli Software"
theme = "hugo-brewm"
enableRobotsTXT = true

[params]
  author = "Napoli Software"
  description = "La community tech ai piedi del Vesuvio"
  showReadingTime = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "eventi"
    name = "Eventi"
    url = "/eventi/"
    weight = 20
